pipeline {
  agent any
  stages {
    stage('Clone repo') {
      steps {
        git 'https://github.com/hammadmajeed/k8s_classtask.git'
      }
    }
    stage('Build Docker Image') {
      steps {
         withCredentials([usernamePassword(passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
  
        }
        sh 'docker tag coin-change malaikawaheed/coin-change:0.0.1'
        sh 'docker push my-registry/coin-change:0.0.1'
        }
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        sh 'kubectl apply -f k8s_deployment.yaml'
        sh 'kubectl expose deployment coin-changing --type=LoadBalancer --port=80 --target-port=5000'
      }
      post {
        success {
          echo "Application deployed successfully to k8s!"
        }
        failure {
          echo "Failed to deploy application!"
        }
      }
    }
  }
}
